apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls-spc-app-07
spec:
  provider: azure
  secretObjects: # k8s secret
  - secretName: tls-secret-csi-app-07
    type: kubernetes.io/tls
    data: 
    - objectName: aks-ingress-cert
      key: tls.key
    - objectName: aks-ingress-cert
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    clientID: 48558c85-1aeb-40ec-b3e8-70f5c71e5841 # Setting this to use workload identity
    keyvaultName: akvaksapp07 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: aks-ingress-cert
          objectType: secret
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3 # the tenant ID for KV