trigger: 
- main

pool:
  vmImage: ubuntu-latest

variables:
  acr_name: improvinginfraacr
  # tag: 1.0.0-$(Build.BuildId)

steps:

- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'AzureCSP_azure_keadilanrak(ad094228-d66a-4aad-acfb-3606b11366a3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t $(acr_name).azurecr.io/webapp:latest app-dotnet
      az acr login -n $(acr_name)
      docker push $(acr_name).azurecr.io/webapp:latest
      docker push $(acr_name).azurecr.io/webapp:latest
      


- script: cat 02_kubernetes_aks/app-deploy.yaml


- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aks'
    azureResourceGroup: 'improvinginfra'
    kubernetesCluster: 'aks-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
