trigger: 
- main

pool:
  vmImage: ubuntu-latest

variables:
  acr_name: improvinginfraacr
  # tag: 1.0.0-$(Build.BuildId)

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'azureacr'
    repository: 'improvinginfraacr'
    command: 'buildAndPush'
    Dockerfile: 'app-dotnet/Dockerfile'
    buildContext: 


      


- script: cat 02_kubernetes_aks/app-deploy.yaml


- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aks'
    azureResourceGroup: 'improvinginfra'
    kubernetesCluster: 'aks-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
