# trigger:
# - main

pool:
  name: azure-vm
  # vmImage: ubuntu-latest

variables:
  tag: 1.0.0-$(Build.BuildId)

steps:

- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'aks-spn-ca'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t aksclusteracr.azurecr.io/webapp:$(tag) app-dotnet
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH,CRITICAL --ignore-unfixed aksclusteracr.azurecr.io/webapp:$(tag)
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH,CRITICAL --ignore-unfixed mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
      az acr login -n aksclusteracr
      docker push aksclusteracr.azurecr.io/webapp:$(tag)

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  inputs:
    rootDirectory: '02_kubernetes_aks'
    targetFiles: 'app-deploy.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '__'
    tokenSuffix: '__'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: true

- script: cat 02_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aks-spn-ca'
    azureResourceGroup: 'aks-cluster'
    kubernetesCluster: 'aks-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
