apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects: # k8s secret
  - secretName: tls-secret-csi-dev
    type: kubernetes.io/tls
    data: 
    - objectName: aks-ingress-cert # aks-cert-tls-dev # 
      key: tls.key
    - objectName: aks-ingress-cert # aks-cert-tls-dev # 
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 5b72dcec-2dfb-47f8-8d3d-accdc505a5c1
    keyvaultName: kvaksingressapp04 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: aks-ingress-cert
          objectType: secret
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3" #  # the tenant ID for KV
